/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "Audio/Engine.h"
#include "GUI/MainWindow.h"
#include "Core/ProjectManager.h"

//==============================================================================
class KentDAWApplication  : public JUCEApplication
{
public:
    //==============================================================================
    KentDAWApplication() : _engine(&_commandsManager) {}

    const String getApplicationName() override       { return ProjectInfo::projectName; }
    const String getApplicationVersion() override    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed() override       { return true; }

    //==============================================================================
    void initialise (const String& commandLine) override
    {
        registerCommands();
        _mainWindow = new MainWindow(_commandsManager, _engine);
    }

    void shutdown() override
    {
    }

    void registerCommands()
    {
        _commandsManager.registerAllCommandsForTarget(this);
        _commandsManager.registerAllCommandsForTarget(getInstance());
    }

    ApplicationCommandTarget * getNextCommandTarget() override
    {
        return JUCEApplication::getNextCommandTarget();
    }

    void getAllCommands(Array<CommandID>& commands) override
    {
        JUCEApplication::getAllCommands(commands);
        _projectManager.getAllCommands(commands);
        _engine.getAllCommands(commands);
        _mainWindow->getAllCommands(commands);
    }

    void getCommandInfo(CommandID commandID, ApplicationCommandInfo & result) override
    {
        JUCEApplication::getCommandInfo(commandID, result);
        _projectManager.getCommandInfo(commandID, result);
        _engine.getCommandInfo(commandID, result);
        _mainWindow->getCommandInfo(commandID, result);
    }

    bool perform(const InvocationInfo & info) override
    {
        ApplicationCommandInfo commandInfo(info.commandID);

        getCommandInfo(info.commandID, commandInfo);

        if (commandInfo.categoryName == "Project Management" || commandInfo.categoryName == "Selection") {
            return _projectManager.perform(info);
        }

        if (commandInfo.categoryName == "Audio") {
            return _engine.perform(info);
        }

        if (commandInfo.categoryName == "Global") {
            return _mainWindow->perform(info);
        }

        return JUCEApplication::perform(info);
    }

    //==============================================================================
    void systemRequestedQuit() override
    {
        quit();
    }

    void anotherInstanceStarted (const String& commandLine) override
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }

private:
    ProjectManager _projectManager;
    ScopedPointer<MainWindow> _mainWindow;
    Audio::Engine _engine;
    ApplicationCommandManager _commandsManager;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(KentDAWApplication)
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (KentDAWApplication)
